language: node_js
node_js:
  - '6'
before_script:
  - npm install
script:
  - npm run test
notifications:
  slack:
    secure: fJn3g6x2danVyRRYKpI/G/m7DPL7e4pCsN79TUZYNP1Okju61wlvUtrme3rcLLYaAI7vvGBFhzyJPWJLrBHvVQh8UWYX81bqTIyF7zh6xdrUscn5Mz/WH0FhdGEx2VODGyhJHa6oLIT6Gg3G+dnuFpp4O5xUWPFHkk+XsBtpoEM=
