var OBJExporter = function() {
  this.buff;
}

OBJExporter.prototype.export = function(meshes) {
  this.buff  = sprintf("// generated by [eisenscript](https://github.com/after12am/eisenscript/)\n");
  this.buff += sprintf("g generative structures\n");
  // write objects data
  for (var i = 0; i < meshes.length; i++) this.exportMesh(meshes[i]);
  return this.buff;
}

OBJExporter.prototype.exportMesh = function(mesh) {
  var that = this;
  var m = mesh.matrix.elements;
  
  mesh.geometry.vertices.forEach(function(v) {
    that.buff += sprintf(
      "v %s %s %s\n", 
      m[0] * v.x + m[1] * v.y + m[2]  * v.z + m[3]  * 1, 
      m[4] * v.x + m[5] * v.y + m[6]  * v.z + m[7]  * 1, 
      m[8] * v.x + m[9] * v.y + m[10] * v.z + m[11] * 1
    );
  });
  
  mesh.geometry.faces.forEach(function(face) {
    that.buff += sprintf(
      "f %s %s %s %s\n", 
      face.a + 1, 
      face.b + 1, 
      face.c + 1,
      face.d !== undefined ? face.d + 1 : ''
    );
  });
}
