var Symbol = {
  Define: 'define',
  Set: 'set',
  Statement: 'statement',
  Rule: 'rule',
  Modifier: 'modifier',
  Maxdepth: 'maxdepth',
  Maxobjects: 'maxobjects',
  Minsize: 'minsize',
  Maxsize: 'maxsize',
  Seed: 'seed',
  Weight: 'weight',
  Background: 'background',
  XShift: 'xshift',
  YShift: 'yshift',
  ZShift: 'zshift',
  RotateX: 'rotatex',
  RotateY: 'rotatey',
  RotateZ: 'rotatez',
  Size: 'size',
  Matrix: 'matrix',
  Color: 'color',
  Hue: 'hue',
  Saturation: 'saturation',
  Brightness: 'brightness',
  Blend: 'blend',
  Alpha: 'alpha'
}