export default class Symbol {
  static get Define() { return 'define'; }
  static get Set() { return 'set'; }
  static get Statement() { return 'statement'; }
  static get Primitive() { return 'primitive'; }
  static get Rule() { return 'rule'; }
  static get Modifier() { return 'modifier'; }
  static get Maxdepth() { return 'maxdepth'; }
  static get Maxobjects() { return 'maxobjects'; }
  static get Minsize() { return 'minsize'; }
  static get Maxsize() { return 'maxsize'; }
  static get Seed() { return 'seed'; }
  static get Weight() { return 'weight'; }
  static get Background() { return 'background'; }
  static get XShift() { return 'xshift'; }
  static get YShift() { return 'yshift'; }
  static get ZShift() { return 'zshift'; }
  static get RotateX() { return 'rotatex'; }
  static get RotateY() { return 'rotatey'; }
  static get RotateZ() { return 'rotatez'; }
  static get Size() { return 'size'; }
  static get Matrix() { return 'matrix'; }
  static get Color() { return 'color'; }
  static get ColorPool() { return 'colorpool'; }
  static get Hue() { return 'hue'; }
  static get Saturation() { return 'saturation'; }
  static get Brightness() { return 'brightness'; }
  static get Blend() { return 'blend'; }
  static get Alpha() { return 'alpha'; }
}
